### ISSUE TITLE
consider upgrading udig target env to eclipse neon3 and Java 8

### ISSUE THREAD

**Issue by nprigour** [locationtech/udig-platform#256]
the current latest version of udig uses luna target environment but suffers from a number of limitations/performance issues like:

- drag handles are not available for moving main toolbar and minimized/fast views
- startup time of the udig product seems to be considerably greater compared to old udig 1.4 

upgrading to eclipse neon target environment may resolve this UI issues and improve performance

**Comment by egouge** [comment]
I "upgraded" some parts of uDig to work on a Neon target.  There were not a lot of changes required to get it to work (at least not the parts I am using) and it seems to be working fine.  I cannot comment on overall performance though as I only use a few parts of uDig.

**Comment by nprigour** [comment]
Hi @egouge ,
What was your OS platform? I have also done some preliminary tests of deploying udig to neon target platform and seems to work smoothly in windows (I just updated the target definition to use  neon plugins, set javaSE env to 1.8 in all plugin's  .classpath files and some very minor code modifications in a couple of plugins). 
However testing it in linux I experienced some undesired behavior when for example doing a right click and selecting 'properties' for a layer in the LayersView or a map in the Project Explorer (an extra empty window was spawn without any exception to indicate the reason why).
Besides that the 2 issues I am mentioning in my first comment seems to be resolved

**Comment by egouge** [comment]
Primarily Windows.  I have done a very small amounts of testing on Mac.  I have not tested on linux, but I will try to find time and report back.

**Comment by fgdrf** [comment]
I was trying to upgrade to Oxygen last month while Eclipse released it. As long as I know it was a straight forward upgrade to fix target-platform issues. Going to push that work to forked repository within the next days. 

Questions: Is it prefered to upgrade to Neon first to support Neon (4.6) stable release ([Neon 3](https://wiki.eclipse.org/Neon/Simultaneous_Release_Plan)) while Oxygen (4.7) might have some problems?

**Comment by nprigour** [comment]
I have also tested it a couple of day ago with oxygen (some code modification is further needed due to the fact that some deprecated API was removed). In oxygen both issues mentioned in my initial comments are resolved but still there I experienced the undesired behavior with the empty windows. I will try to upload a screenshot the coming day to show you the problem I am mentioned.

Concerning your question I would say it is better to go to a more mature version of the platform (providing we resolve issues in all supported OS) and this is definetely  Neon.

**Comment by fgdrf** [comment]
Interesting, havent such an issue on windows based on Oxygen release. Please have a look at the branch I pushed : https://github.com/fgdrf/udig-platform/tree/upgrade_eclipse_oxygen

I haven't upgraded `Bundle-RequiredExecutionEnvironment` to 1.8 yet..

**Comment by nprigour** [comment]
Hi @fgdrf ,

I tested the branch you pushed and the issue with the extra window popping up still exists (tested on Ubuntu 16.0 and 14.10 distributions). From a more thorough look I discover that the issue with the extra window popup is related with whether you create a new Shell() or reuse an existing one. 
Below and within the attached zip, I am providing 2 patches (they should apply on the branch you mention above https://github.com/fgdrf/udig-platform/tree/upgrade_eclipse_oxygen) 

1. The first patch (udig-platform_oxygen.patch) fixes some extra issues related to upgrade in oxygen:
       - ListenerList constructor argument allowed value are 0 or 1. The value 3 you specified is not allowed.
       -  TabbedPropertyViewPlugin.getPlugin().getLog().log(..) is not visible so I replaced it with a more appropriate one 

2. The second patch (udig-platform_oxygen_shell_issue.patch) fixes the extra dialog issue in most cases (it now only occurs when left clicking on a layer or map and selecting "Properties". This context menu option is controlled by  org.eclipse.ui.dialogs.PropertyDialogAction and I cannot intervene).  

[upgrade-oxygen-patch.zip](https://github.com/locationtech/udig-platform/files/1466324/upgrade-oxygen-patch.zip)

**Comment by nprigour** [comment]
Eventually I figure out and resolved the problem with the remaining windows (see list item 2 in my previous comment). It was due to a call that was made in org.locationtech.udig.ui.ZoomingDialog. I am providing an extra patch that address this

[udig-platform_oxygen_shell_issue_additional.zip](https://github.com/locationtech/udig-platform/files/1466719/udig-platform_oxygen_shell_issue_additional.zip)

**Comment by fgdrf** [comment]
@nprigour Would you please create (a) pull request(s) with your two fixed for this branch? So we can merge it and shows you as a committer for the fix! Thanks for testing with this branch

**Comment by nprigour** [comment]
Do you want the pull request to be created in [https://github.com/fgdrf/udig-platform/tree/upgrade_eclipse_oxygen](https://github.com/fgdrf/udig-platform/tree/upgrade_eclipse_oxygen) or for the master branch?
I am asking because although the patches were provided based on your oxygen upgrade branch I think they are perfectly valid also for the current udig master version.

**Comment by nprigour** [comment]
Hi @fgdrf,
I just created a pull request in your  [ https://github.com/fgdrf/udig-platform/tree/upgrade_eclipse_oxygen ](https://github.com/fgdrf/udig-platform/tree/upgrade_eclipse_oxygen ) forked branch

**Comment by fgdrf** [comment]
Hi @nprigour, merged it onto the oxygen branch. Do you mean the cleanup of ZoomShellProvider and usage of SameShellProvider can be applied on master as well? And this would be possible because of Luna jface release provides this class already?

**Comment by nprigour** [comment]
Yes SameShellProvider is present in latest luna jface library (org.eclipse.jface_3.10.2.v20141021-1035.jar) so I think there is no issue with applying it in master branch

**Comment by nprigour** [comment]
What is the status of this issue? Is there any other reason that prohibits upgrading to a newer eclipse version (neon or luna)?

**Comment by nprigour** [comment]
What about while upgrading to a newer eclipse version addressing also the following:
-  upgrade to java 8 
-  upgrade to a more updated geotools version (suggested is 19.0)

I have already done this in the local application I am working with so I can provide assistance (I left the decision whether we do this on  #275 or on by creating separate pull requests to you)

**Comment by fgdrf** [comment]
IMHO we should address GeoTools update to stable version seperatly...

Does the upgrade to Oxygen imply that it is required to have Java 1.8 at runtime? If so, we should
* update ``Bundle-RequiredExecutionEnvironment: JavaSE-1.8`` in Manifest files
* update installer and void packaging JRE (see also #225)

**Comment by fgdrf** [comment]
#275 merged to master, done
